### ISSUE TITLE
Lake intersecting viewport is rendered wrong

### ISSUE THREAD

**Issue by habi** [enzet/map-machine#143] opened 2022-10-18 07:52 UTC
I'd like to produce a high-resolution render of [a campsite](https://www.openstreetmap.org/way/359338758) and can do this by issuing `map-machine render --boundary-box=6.712,46.802,6.723,46.807 --zoom=16 --output=out/vd8.svg`.

This does render the lake bordering the campsite weirdly, e.g. glitches out with the intersection of the campsite.
I know that rendering of lakes or larger water bodies is complicated, but how could I generate a nice map of this campsite?

![map](https://user-images.githubusercontent.com/1651235/196369008-8cb4f6e7-de51-4124-80cf-68efa3b1f9d5.png)

**Comment by habi** [comment] 2022-10-18 08:12
Two observations in relation to the lake rendering

- `map-machine render --coordinates=46.805,6.715 --zoom=16 --output=out/bad.svg` 
- `map-machine render --coordinates 46.805,6.755 --zoom=16 --output=out/good.svg`

**Comment by enzet** [comment] 2022-10-20 21:58
Hello, @habi!

Thank you for the issue.  I'm afraid, this is really a hard one.  Map Machine downloads only ways that at least partly present inside boundary box, so it doesn't have enough information about lake shape.

I may provide two ways to fix that:
  1. Easy one is to just try to download more data.  I'll add an option to specify another bigger boundary box for downloading.
  2. Hard one is to try to honestly compute lake shape analysing way direction.

I think, I want to start with the first one and then will continue with the second one.

**Comment by habi** [comment] 2022-10-21 06:34
There's no option for 'discarding' a feature lake in map-machine?
Or could I somehow twiddle with the downloaded XML and try to remove all 'traces' of the lake?

**Comment by enzet** [comment] 2022-10-21 20:19
Sure, you just need to either edit default scheme file or use a custom scheme file.

E.g. use [`no_water.yml`](url) and `--scheme` option:

```shell
map-machine render --coordinates=46.805,6.715 --zoom=16 --output=out/bad0.svg --scheme no_water.yml
```

`no_water.yml` is just `map_machine/scheme/default.yml` with the following diff:

```diff
   - tags: {natural: water}
     exception: {intermittent: "yes"}
     style:
-      fill: water_color
-      # stroke: water_border_color
-      # stroke-width: 1.0
+      # fill: water_color
+      stroke: water_border_color
+      stroke-width: 1.0
     priority: 21.0
```

**Comment by enzet** [comment] 2022-10-26 21:14
This is a duplicate of #120.

**Closed by enzet** 2022-10-26 21:14 UTC
Labels: bug, duplicate
